# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
# An action often accepts or requires inputs and generates outputs that you can use. 
# For example, an action might require you to specify a path to a file, the name of a label, 
# or other data it will use as part of the action processing.
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}